### ISSUE TITLE
Not connecting anymore

### ISSUE THREAD

**Issue by kain1000000** [beameio/beame-insta-ssl#25] opened 2017-02-19 19:58 UTC
Hi.

With help from this forum I was able to get beame to work.
However, today , though the tunnel is being created I can't seem to be able to connect to it no matter what I try. As an aside, trying with ngrok still lets me connect though.

I use  beame-insta-ssl tunnel 80 http --fqdn cfkvikeccxl6tgoe.v1.p.beameio.net    to start my connection.

Thanks in advance for any help

**Comment by zglozman** [comment] 2017-02-19 20:41
Are you running a web server on port 80?

**Comment by kain1000000** [comment] 2017-02-19 20:49
Yes I am

**Comment by kain1000000** [comment] 2017-02-22 08:29
Hi. I'm still having this issue. Please, is there anyone who can help?

**Comment by zglozman** [comment] 2017-02-22 14:27
Can pls share some details? General descriptions does help

**Comment by kain1000000** [comment] 2017-02-23 11:23
kain1000000@KAINTHE7TH MINGW32 ~
$ beame-insta-ssl tunnel 80 http --fqdn cfkvikeccxl6tgoe.v1.p.beameio.net
Starting tunnel https://cfkvikeccxl6tgoe.v1.p.beameio.net -> http://localhost:80

**Comment by kain1000000** [comment] 2017-02-23 11:24
The above is what i get after starting the tunnel

**Comment by kain1000000** [comment] 2017-02-23 11:34
I can open the link on the server, but not on any other device/computer.

I get a "Firefox can't establish a connection to the server at localhost.

1. The Site could be temporarily unavailable or too busy. Try again in a few moments.

2. If you are unable to load any ages, check you mobile device's data or WiFi connection."

**Comment by ilyash** [comment] 2017-02-23 16:31
Please run

`BEAME_LOG_LEVEL=DEBUG beame-insta-ssl tunnel 80 http --fqdn cfkvikeccxl6tgoe.v1.p.beameio.net`

There should be debug information which may have some clues

**Comment by ilyash** [comment] 2017-02-23 16:41
I see you were using the tunnel few hours ago. There were few requests with traffic in both directions. Total traffic for last connection was about 2.5K in one direction and about 16K in the other direction. Things look OK from the perspective of the "edge" server, the server you are connecting to when using the tunnel.

**Comment by kain1000000** [comment] 2017-02-23 18:21
$ BEAME_LOG_LEVEL=DEBUG beame-insta-ssl tunnel 80 http --fqdn cfkvikeccxl6tgoe.v1.p.beameio.net
Starting tunnel https://cfkvikeccxl6tgoe.v1.p.beameio.net -> http://localhost:80

**Comment by kain1000000** [comment] 2017-02-23 23:59
Please what command prompt should i use to run the command? When i try, all i get is the above

**Comment by zglozman** [comment] 2017-02-24 00:05
You are opening  it with https right ?

**Comment by kain1000000** [comment] 2017-02-24 07:41
Yes I am.

**Comment by ilyash** [comment] 2017-04-23 14:39
Probably duplicate of #27 . Please re-open if needed.

**Closed as completed by ilyash** 2017-04-23 14:39 UTC
