### ISSUE TITLE
Host is unreachable

### ISSUE THREAD

**Issue by rsquared24** [beameio/beame-insta-ssl#47] opened 2017-08-22 02:13 UTC
Hi team,

Ive setup as per the docs however when I start the tunnel (https://z5h01j4j91rkm9gl.v1.p.beameio.net/) it does not connect (site cannot be reached)

Ran it with the debug command `BEAME_LOG_LEVEL=DEBUG beame-insta-ssl tunnel make --dst 3000 --proto http` and got the following output

```
[2017-08-22 12:06:28] [BeameCreds] DEBUG: list  undefined
[2017-08-22 12:06:28] [BeameCreds] DEBUG: list  null
Starting tunnel https://z5h01j4j91rkm9gl.v1.p.beameio.net -> http://localhost:3000
[2017-08-22 12:06:28] [BeameStore] DEBUG: checkValidity: fqdn, start, end', z5h01j4j91rkm9gl.v1.p.beameio.net, 1503365746000, 1534901746000
[2017-08-22 12:06:30] [BeameStore] DEBUG: checkValidity: fqdn, start, end', z5h01j4j91rkm9gl.v1.p.beameio.net, 1503365746000, 1534901746000
Timeout waiting for NTP response.
```

localhost:3000 (express) is working fine.

Any help would apprecaited

Thanks,

Ron

**Comment by AlexzxelA** [comment] 2017-08-22 04:16
Hi Ron, it looks as if your domain name is not set in DNS. Please use following command and retry:
`beame-insta-ssl creds setDns --fqdn z5h01j4j91rkm9gl.v1.p.beameio.net --useBestProxy true`
Cheers,
Alex

**Comment by rsquared24** [comment] 2017-08-24 04:09
Hi Alex,

Its currently timing out with the message "Timeout waiting for NTP response" when running the command you specified.

I've turned off the firewall to see if that was causing and issue and still no good

Thanks,

Ron

**Comment by AlexzxelA** [comment] 2017-08-25 07:06
Hi Ron, it can happen if you are behind some proxy that blocks ntp port (123). We've already prepared a workaround, it will be released next week

**Comment by pt6000** [comment] 2017-11-08 08:24
Hi, I also encountered the same problem and it has been a week already. Pls help and let me know what I should do. Thanks. 

===========================================================
[2017-11-08 16:14:55] [NeDBServices] INFO: All collections loaded
[2017-11-08 16:14:55] [NeDBServices] INFO: NeDB started successfully
[2017-11-08 16:14:55] [Bootstrapper] INFO: Beame-gatekeeper config files ensured
[2017-11-08 16:14:55] [Bootstrapper] INFO: Beame-gatekeeper NeDB DB updated successfully
[2017-11-08 16:14:55] [Bootstrapper] INFO: beame-gatekeeper bootstrapped successfully
[2017-11-08 16:14:55] [CredentialManager] INFO: Creating credentials for GatewayServer
[2017-11-08 16:14:55] [BeameStore] INFO: Registering credential r9qnltvhnq98snqx.v1.p.beameio.net ...
[2017-11-08 16:14:55] [CredentialManager] INFO: Creating credentials for GatekeeperLoginManager
[2017-11-08 16:14:55] [BeameStore] INFO: Registering credential r9qnltvhnq98snqx.v1.p.beameio.net ...
[2017-11-08 16:14:55] [CredentialManager] INFO: Creating credentials for MatchingServer
[2017-11-08 16:14:55] [BeameStore] INFO: Registering credential r9qnltvhnq98snqx.v1.p.beameio.net ...
Timeout waiting for NTP response.
Timeout waiting for NTP response.

**Comment by ilyash** [comment] 2017-11-08 09:19
What's your time zone?

Is your clock correct?

Which version of Beame Gatekeeper are you using?

Please open a ticket with the answers at https://github.com/beameio/beame-gatekeeper/issues .

**Closed as completed by ilyash** 2017-11-08 09:19 UTC

**Comment by pt6000** [comment] 2017-11-09 02:08
Hi, 
My time zone is (UTC+8:00) Kuala Lumpur, Singapore and my clock should be correct. 
I installed the gatekeeper from "https://www.beame.io/" which directed me to another website for installation and I am not sure the version for the gatekeeper. 
 By the way, I can only go to "https://github.com/beameio/beame-gatekeeper-docker". I can't  see this link "https://github.com/beameio/beame-gatekeeper". 
Thanks.

**Comment by ilyash** [comment] 2017-11-12 10:57
This issue belongs to beame-insta-ssl product and you are having problems with beame-gatekeeper. Since it's the wrong product, the issue is closed. It will be confusing for people to see unrelated content in this thread.

Please open a ticket with the answer at https://github.com/beameio/beame-gatekeeper/issues . Ideally, link to this issue from there.

Did you execute the `npm install -g beame-gatekeeper` command?

**Comment by pt6000** [comment] 2017-11-13 08:26
Thanks for the reply. 
I exceuted this command "npm install -g beame-gatekeeper" before "beame-gatekeeper creds getCreds --regToken". It seeems there is no such link "https://github.com/beameio/beame-gatekeeper" but I can find "https://github.com/beameio/beame-gatekeeper-docker".
